// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// `FlutterFire` configuration options.
///
/// This file contains Firebase configuration for Chess Tactics Master.
///
/// **IMPORTANT**: To use real Firebase:
/// 1. Create Firebase project at https://console.firebase.google.com
/// 2. Run: flutterfire configure --project=yourwish-chess
/// 3. Download google-services.json (Android) and GoogleService-Info.plist (iOS)
/// 4. Update .env with actual credentials
///
/// For development, this uses placeholder values from .env file.
/// For production, use actual Firebase project credentials.

class DefaultFirebaseOptions {
  /// Get Firebase options from environment or use development defaults
  static FirebaseOptions get currentPlatform {
    final apiKey = dotenv.env['FIREBASE_API_KEY'] ??
        'AIzaSyDn5Bk0Xz9W2j7K4L5M6N7O8P9Q0R1S2T';
    final appId =
        dotenv.env['FIREBASE_APP_ID'] ?? '1:234567890:web:abcdef1234567890ghij';
    final messagingSenderId =
        dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '234567890';
    final projectId = dotenv.env['FIREBASE_PROJECT_ID'] ?? 'yourwish-chess';
    final authDomain =
        dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'yourwish-chess.firebaseapp.com';
    final databaseURL = dotenv.env['FIREBASE_DATABASE_URL'] ??
        'https://yourwish-chess.firebaseio.com';
    final storageBucket =
        dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'yourwish-chess.appspot.com';

    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      databaseURL: databaseURL,
      storageBucket: storageBucket,
      iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.yourwish.chess',
    );
  }
}
